plugins {
	id 'fabric-loom' version '1.10-SNAPSHOT'
	id 'maven-publish'
	id("org.jetbrains.kotlin.jvm") version("2.0.0")
}

version = project.mod_version
group = project.maven_group

base {
	archivesName = project.archives_base_name
}

repositories {
	mavenCentral()
	maven { url = "https://maven.fabricmc.net/" } // Ensure Fabric Maven is included
	maven { url = "https://maven.impactdev.net/repository/development/" }
	maven {
		name = 'CurseForge'
		url = 'https://www.cursemaven.com'
	}
	maven {
		name = 'Kotlin for Forge'
		url = 'https://thedarkcolour.github.io/KotlinForForge/'
	}
	maven {
		name = 'Kotlin for Fabric'
		url = 'https://maven.fabricmc.net/net/fabricmc/fabric-language-kotlin/'
	}
	maven {
		name = "Fuzs Mod Resources"
		url = "https://raw.githubusercontent.com/Fuzss/modresources/main/maven/"
	}
	maven { url 'https://maven.nucleoid.xyz' }
}

fabricApi {
	configureDataGeneration {
		client = true
	}
}

dependencies {
	minecraft "com.mojang:minecraft:1.21.1"
	mappings "net.fabricmc:yarn:1.21.1+build.3:v2"
	modImplementation "net.fabricmc:fabric-loader:0.16.14"
	modImplementation "net.fabricmc.fabric-api:fabric-api:0.115.6+1.21.1"
	modImplementation "net.fabricmc.fabric-api:fabric-networking-api-v1:0.115.6+1.21.1"
	modImplementation "com.cobblemon:fabric:1.6.1+1.21.1"
	implementation "org.jetbrains.kotlin:kotlin-stdlib:2.0.0"
	implementation "org.jetbrains.kotlin:kotlin-reflect:2.0.0"
	modImplementation "me.lucko:fabric-permissions-api:0.3.1"
}

processResources {
	inputs.property "version", project.version
	filesMatching("fabric.mod.json") {
		expand "version": inputs.properties.version
	}
}

tasks.withType(JavaCompile).configureEach {
	options.release = 21
}

tasks.withType(org.jetbrains.kotlin.gradle.tasks.KotlinCompile).configureEach {
	kotlinOptions {
		jvmTarget = "21"
	}
}

java {
	withSourcesJar()
	sourceCompatibility = JavaVersion.VERSION_21
	targetCompatibility = JavaVersion.VERSION_21
}

jar {
	inputs.property "archivesName", project.base.archivesName
	from("LICENSE") {
		rename { "${it}_${inputs.properties.archivesName}" }
	}
}

publishing {
	publications {
		create("mavenJava", MavenPublication) {
			artifactId = project.archives_base_name
			from components.java
		}
	}
	repositories {
		// Add repositories to publish to here
	}
}